#!/usr/bin/env php
<?php

const PASTA_PUBLIC = __DIR__ . '/public';
require 'system/Core/iniciar_app.php';


//Exemplo de como impedir acesso à forja baseado em alguma condição
// if (AMBIENTE !== 'desenvolvimento') {
//     die("\n\033[91m# CLI não disponível fora do ambiente de desenvolvimento.\033[0m\n");
// }

try {

    new \Hefestos\CLI\CLI($argv);
    
} catch (\Throwable $th) {
    echo 
    "\033[91m -> Erro encontrado: \033[0m" . $th->getMessage() . "\n" . 
    "\033[91m -> Na linha: \033[0m" . $th->getLine() . "\n" . 
    "\033[91m -> Do arquivo: \033[0m" . $th->getFile();
}