#!/usr/bin/env php
<?php

if( PHP_VERSION < '8.0.0'){
    die('PHPratico precisa do PHP versão 8.0.0 ou mais alta.');
}

require 'app/Config/constantes.php';
require 'system/auxiliares.php';
require 'system/autoloader.php';

new \System\CLI($argv);

?>